### ISSUE TITLE
Warning messages in v2.0.0

### ISSUE THREAD

**Issue by debsush** [datastorm-open/rAmCharts#43] opened 2016-04-21 03:01 UTC
I get the following new warning messages in v2.0.0
Warning in FUN(X[[i]], ...) :
  You should use setter for property 'creditsPosition'
Warning in FUN(X[[i]], ...) :
  You should use setter for property 'allLabels'

How to fix these?

**Comment by bthieurmel** [comment] 2016-04-21 05:41
Example ?

**Comment by Djaiff** [comment] 2016-04-21 07:10
Hi,

I think, you set the properties with the method 'setProperties' instead of using the constructor function or the dedicated setters. These two alternatives are more sure since there is a validity check of the argument provided (for most of case).

So this is probably a warning about the syntax, if not, could you give us an example ?

Thanks

**Comment by debsush** [comment] 2016-04-21 08:52
stockpanels_Fund <<- lapply(1:1, function(i)
    (stockPanel(id='FD',
                Title="Main",
                zoomOutOnDataUpdate = FALSE,
                creditsPosition="top-left",
                precision=2,
                showCategoryAxis= FALSE,
                stockGraphs=stockgraphs_Fund,
                allowTurningOff = FALSE,
                thousandsSeparator=",",
                recalculateToPercents="never",
                        allLabels = list(list(
                          x= 3,
                          y= 6,
                          text= "Let us Try rAmCharts",
                          align= "center",
                          color="#2f4f4f",
                          bold=FALSE,
                          size= 12)  
                        ),
                borderAlpha = .2)%>>%
       setValueAxes(valueAxis_fund)%>>%
       setStockLegend(labelText= '[[title]]',
                      periodValueTextComparing = '[[percents.value.close]]%',
                      periodValueTextRegular = '[[value.close]]'
       )))

**Comment by Djaiff** [comment] 2016-04-29 15:06
The problem is now fixed in the current version on Github.

**Closed as completed by Djaiff** 2016-04-29 15:06 UTC
